# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  #adapter: sqlite3
  #pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  #timeout: 5000
  adapter: mysql2
  encoding: utf8
  database: flight_scraping
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: 127.0.0.1
  port: 3306
  #socket: /var/run/mysqld/mysqld.sock

development:
  adapter: mysql2
  encoding: utf8
  database: flight_scraping
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: 127.0.0.1
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: flight_scraping
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: 127.0.0.1
  port: 3306
  #socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  password: 
  host: 127.0.0.1
  port: 3306
  #socket: /var/run/mysqld/mysqld.sock
